// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osc_command.proto

package uk.ac.salford.edu.a3.aphillips.sensoriottests.proto;

public final class OscCommand {
  private OscCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OSCCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OSCCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string target = 1;</code>
     */
    boolean hasTarget();
    /**
     * <code>required string target = 1;</code>
     */
    java.lang.String getTarget();
    /**
     * <code>required string target = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>required .OSCCommand.ValueType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .OSCCommand.ValueType type = 2;</code>
     */
    uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType getType();

    /**
     * <code>optional int32 value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional int32 value = 3;</code>
     */
    int getValue();

    /**
     * <code>optional string s_value = 4;</code>
     */
    boolean hasSValue();
    /**
     * <code>optional string s_value = 4;</code>
     */
    java.lang.String getSValue();
    /**
     * <code>optional string s_value = 4;</code>
     */
    com.google.protobuf.ByteString
        getSValueBytes();
  }
  /**
   * Protobuf type {@code OSCCommand}
   */
  public  static final class OSCCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OSCCommand)
      OSCCommandOrBuilder {
    // Use OSCCommand.newBuilder() to construct.
    private OSCCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OSCCommand() {
      target_ = "";
      type_ = 0;
      value_ = 0;
      sValue_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OSCCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              target_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType value = uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              value_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sValue_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.internal_static_OSCCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.internal_static_OSCCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.class, uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.Builder.class);
    }

    /**
     * Protobuf enum {@code OSCCommand.ValueType}
     */
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NUMBER = 0;</code>
       */
      NUMBER(0),
      /**
       * <code>STRING = 1;</code>
       */
      STRING(1),
      ;

      /**
       * <code>NUMBER = 0;</code>
       */
      public static final int NUMBER_VALUE = 0;
      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueType valueOf(int value) {
        return forNumber(value);
      }

      public static ValueType forNumber(int value) {
        switch (value) {
          case 0: return NUMBER;
          case 1: return STRING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValueType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValueType[] VALUES = values();

      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValueType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:OSCCommand.ValueType)
    }

    private int bitField0_;
    public static final int TARGET_FIELD_NUMBER = 1;
    private volatile java.lang.Object target_;
    /**
     * <code>required string target = 1;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string target = 1;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string target = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required .OSCCommand.ValueType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .OSCCommand.ValueType type = 2;</code>
     */
    public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType getType() {
      uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType result = uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType.valueOf(type_);
      return result == null ? uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType.NUMBER : result;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private int value_;
    /**
     * <code>optional int32 value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 value = 3;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int S_VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object sValue_;
    /**
     * <code>optional string s_value = 4;</code>
     */
    public boolean hasSValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string s_value = 4;</code>
     */
    public java.lang.String getSValue() {
      java.lang.Object ref = sValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s_value = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSValueBytes() {
      java.lang.Object ref = sValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, target_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, value_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand)) {
        return super.equals(obj);
      }
      uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand other = (uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand) obj;

      boolean result = true;
      result = result && (hasTarget() == other.hasTarget());
      if (hasTarget()) {
        result = result && getTarget()
            .equals(other.getTarget());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && (getValue()
            == other.getValue());
      }
      result = result && (hasSValue() == other.hasSValue());
      if (hasSValue()) {
        result = result && getSValue()
            .equals(other.getSValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue();
      }
      if (hasSValue()) {
        hash = (37 * hash) + S_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getSValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OSCCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OSCCommand)
        uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.internal_static_OSCCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.internal_static_OSCCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.class, uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.Builder.class);
      }

      // Construct using uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.internal_static_OSCCommand_descriptor;
      }

      public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand getDefaultInstanceForType() {
        return uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.getDefaultInstance();
      }

      public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand build() {
        uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand buildPartial() {
        uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand result = new uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sValue_ = sValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand) {
          return mergeFrom((uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand other) {
        if (other == uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          bitField0_ |= 0x00000001;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasSValue()) {
          bitField0_ |= 0x00000008;
          sValue_ = other.sValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTarget()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object target_ = "";
      /**
       * <code>required string target = 1;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string target = 1;</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string target = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string target = 1;</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 1;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 1;</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>required .OSCCommand.ValueType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .OSCCommand.ValueType type = 2;</code>
       */
      public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType getType() {
        uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType result = uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType.valueOf(type_);
        return result == null ? uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType.NUMBER : result;
      }
      /**
       * <code>required .OSCCommand.ValueType type = 2;</code>
       */
      public Builder setType(uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .OSCCommand.ValueType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>optional int32 value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 value = 3;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 3;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sValue_ = "";
      /**
       * <code>optional string s_value = 4;</code>
       */
      public boolean hasSValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string s_value = 4;</code>
       */
      public java.lang.String getSValue() {
        java.lang.Object ref = sValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sValue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s_value = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSValueBytes() {
        java.lang.Object ref = sValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s_value = 4;</code>
       */
      public Builder setSValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s_value = 4;</code>
       */
      public Builder clearSValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sValue_ = getDefaultInstance().getSValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s_value = 4;</code>
       */
      public Builder setSValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sValue_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OSCCommand)
    }

    // @@protoc_insertion_point(class_scope:OSCCommand)
    private static final uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand();
    }

    public static uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OSCCommand>
        PARSER = new com.google.protobuf.AbstractParser<OSCCommand>() {
      public OSCCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OSCCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OSCCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OSCCommand> getParserForType() {
      return PARSER;
    }

    public uk.ac.salford.edu.a3.aphillips.sensoriottests.proto.OscCommand.OSCCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OSCCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OSCCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021osc_command.proto\"\206\001\n\nOSCCommand\022\016\n\006ta" +
      "rget\030\001 \002(\t\022#\n\004type\030\002 \002(\0162\025.OSCCommand.Va" +
      "lueType\022\r\n\005value\030\003 \001(\005\022\017\n\007s_value\030\004 \001(\t\"" +
      "#\n\tValueType\022\n\n\006NUMBER\020\000\022\n\n\006STRING\020\001B5\n3" +
      "uk.ac.salford.edu.a3.aphillips.sensoriot" +
      "tests.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OSCCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OSCCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OSCCommand_descriptor,
        new java.lang.String[] { "Target", "Type", "Value", "SValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
