# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osc_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='osc_command.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11osc_command.proto\"\x9a\x01\n\nOSCCommand\x12\x0e\n\x06target\x18\x01 \x02(\t\x12#\n\x04type\x18\x02 \x02(\x0e\x32\x15.OSCCommand.ValueType\x12\r\n\x05value\x18\x03 \x01(\x05\x12\x0f\n\x07s_value\x18\x04 \x01(\t\x12\x12\n\ntime_stamp\x18\x05 \x01(\x01\"#\n\tValueType\x12\n\n\x06NUMBER\x10\x00\x12\n\n\x06STRING\x10\x01\x42\x35\n3uk.ac.salford.edu.a3.aphillips.sensoriottests.proto')
)



_OSCCOMMAND_VALUETYPE = _descriptor.EnumDescriptor(
  name='ValueType',
  full_name='OSCCommand.ValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NUMBER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=141,
  serialized_end=176,
)
_sym_db.RegisterEnumDescriptor(_OSCCOMMAND_VALUETYPE)


_OSCCOMMAND = _descriptor.Descriptor(
  name='OSCCommand',
  full_name='OSCCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='OSCCommand.target', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='OSCCommand.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='OSCCommand.value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s_value', full_name='OSCCommand.s_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='OSCCommand.time_stamp', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OSCCOMMAND_VALUETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=176,
)

_OSCCOMMAND.fields_by_name['type'].enum_type = _OSCCOMMAND_VALUETYPE
_OSCCOMMAND_VALUETYPE.containing_type = _OSCCOMMAND
DESCRIPTOR.message_types_by_name['OSCCommand'] = _OSCCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OSCCommand = _reflection.GeneratedProtocolMessageType('OSCCommand', (_message.Message,), dict(
  DESCRIPTOR = _OSCCOMMAND,
  __module__ = 'osc_command_pb2'
  # @@protoc_insertion_point(class_scope:OSCCommand)
  ))
_sym_db.RegisterMessage(OSCCommand)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3uk.ac.salford.edu.a3.aphillips.sensoriottests.proto'))
# @@protoc_insertion_point(module_scope)
